name: CD/API/create-degree-plan

env:
  AWS_REGION: us-east-1                     
  FUNCTION_NAME: createDegreePlan    
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main
    paths:
      - "src/api/${{env.FUNCTION_NAME}}/**"
      - ".github/workflows/api/${{env.FUNCTION_NAME}}.yml"

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip & deploy
        run: |
          cd src/api/${{ env.FUNCTION_NAME }}
          npm install
          zip -r lambda.zip .
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --zip-file fileb://lambda.zip