name: CD/API/create-degree-plan

on:
  push:
    branches:
      - main
    paths:
      - "src/api/createDegreePlan/**"
      - ".github/workflows/cd-createDegreePlan.yml"

env:
  FUNCTION_NAME: createDegreePlan

jobs:
  deploy:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies and zip
        run: |
          cd src/api/${{env.FUNCTION_NAME}}
          npm install
          zip -r build.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --zip-file fileb://src/api/${{env.FUNCTION_NAME}}/build.zip \
          --region ${{ env.AWS_REGION }} \
          --handler ${{ env.FUNCTION_NAME }}.handler \
          --environment Variables={ \
              NEO4J_HOST=${{env.FUNCTION_NAME}}, \
              NEO4J_PASSWORD=${{secrets.NEO4J_PASSWORD}}, \
              NEO4J_USERNAME=${{secrets.NEO4J_USERNAME}} |
            }
