name: Tests
on: [push,pull_request]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install modules
        run: pnpm i

      - name: Run ESlint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: npm i
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          PORT: 3000
        with:
          build: npm run build --prefix ./apps/client
          start: npm run start --prefix ./apps/client
          project: ./apps/client
          
  report-error-to-discord:
    runs-on: ubuntu-latest
    needs: [test-frontend,style-check]
    if: always() && (needs.style-check.result == 'failure' || needs.test-frontend.result == 'failure')
    steps:
      - name: Needs context
        env:
          NEEDS_CONTEXT: ${{ toJSON(needs) }}

      - name: Send discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Tests have failed.'
