name: Tests
on: [push, pull_request]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: pnpm/action-setup@v2.1.0
      #   with:
      #     version: 6.0.2

      # - name: Install modules
      #   run: pnpm i

      # - name: Run ESlint
      #   run: pnpm lint

      # - name: Run Prettier
      #   run: pnpm format

      - name: Try to fail
        run: exit 1
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Install modules
      #   run: npm i

      - name: Try to fail
        run: exit 1

      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   env:
      #     PORT: 3000
      #   with:
      #     build: npm run build --prefix ./apps/client
      #     start: npm run start --prefix ./apps/client
      #     project: ./apps/client

  report-error-to-discord:
    runs-on: ubuntu-latest
    needs: [test-frontend, style-check]
    if: always() && (needs.style-check.result == 'failure' || needs.test-frontend.result == 'failure')
    steps:
    - name: Send Discord message
      uses: fjogeleit/http-request-action@v1
      env:
        # WORKFLOW_RUN_URL: ${{ format("{0}/{1}/runs/{2}", env.GITHUB_SERVER_URL, env.GITHUB_REPOSITORY, env.GITHUB_RUN_ID) }}
        WORKFLOW_RUN_URL: ${{ format('{{Hello {0} {1} {2}!}}', 'Mona', 'the', 'Octocat') }}
      with:
        url: "${{ secrets.DISCORD_WEBHOOK }}"
        method: "POST"
        contentType: "application/json"
        data: |
            {
              "content": "<@&969598441980325888>",
              "allowed_mentions": { "roles": ["969598441980325888"] },
              "username": "GitHub",
              "avatar_url": "https://cdn-icons-png.flaticon.com/512/25/25231.png",
              "embeds": [
                  {
                      "title": "Workflow Status",
                      "description": "Tests have failed.",
                      "color": 16740464,
                      "url": ${{ format('{0}/{1}/runs/{2}', env.GITHUB_SERVER_URL, env.GITHUB_REPOSITORY, env.GITHUB_RUN_ID) }}
                  }
              ]
            }