name: Tests
on: [push, pull_request]
jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2

      - name: Install modules
        run: pnpm i

      - name: Run ESlint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm i

      - name: Cypress & build
        uses: cypress-io/github-action@v2
        env:
          PORT: 3000
          CYPRESS_NEO4J_HOST: ${{ secrets.NEO4J_HOST }}
          CYPRESS_NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          CYPRESS_NEO4J_USERNAME: ${{ secrets.NEO4J_USERNAME }}
        with:
          build: npm run build --prefix ./apps/client
          start: npm run start --prefix ./apps/client
          project: ./apps/client

  send-failure-to-discord:
    runs-on: ubuntu-latest
    needs: [test-frontend, style-check]
    if: always() && (needs.test-frontend.result == 'failure' || needs.style-check.result == 'failure')
    steps:
      - name: Send failure message to Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.DISCORD_WEBHOOK }}"
          method: "POST"
          contentType: "application/json"
          data: |
            {
              "content": "<@&969598441980325888>",
              "allowed_mentions": { "roles": ["969598441980325888"] },
              "username": "GitHub",
              "avatar_url": "https://cdn-icons-png.flaticon.com/512/25/25231.png",
              "embeds": [
                  {
                      "title": "Status - ${{ github.workflow }}",
                      "description": "Failed. See more at the link above.",
                      "color": 16740464,
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
              ]
            }

  send-success-to-discord:
    runs-on: ubuntu-latest
    needs: [test-frontend, style-check]
    if: needs.test-frontend.result == 'success' && needs.style-check.result == 'success'
    steps:
      - name: Send success message to Discord
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.DISCORD_WEBHOOK }}"
          method: "POST"
          contentType: "application/json"
          data: |
            {
              "content": "<@&969598441980325888>",
              "allowed_mentions": { "roles": ["969598441980325888"] },
              "username": "GitHub",
              "avatar_url": "https://cdn-icons-png.flaticon.com/512/25/25231.png",
              "embeds": [
                  {
                      "title": "Status - ${{ github.workflow }}",
                      "description": "Success. See more at the link above.",
                      "color": 7405424,
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
              ]
            }
